### ISSUE TITLE
False Notification when somebody unsubscribes

### ISSUE THREAD

**Issue by Setup007** [nmynarcik/youtube-sub-alert#4]
Hello there!
I recently discovered a bug, that another sub is being shown instead as a "new sub", because of the false assumption, that both lists are still "sorted" in the same way.
In the utilities.js I had to do this:
`Array.prototype.diff = function(a) {
	var notFound = true;
outerLoop:
	  for(var i = 0; i < this.length; i++){
		  notFound = true;	
innerLoop:
		  for(var j=0; j< a.length; j++){
			  if(this[i].name === a[j].name){				
				notFound=false;		
				break innerLoop;
			  }			
		  }
		  if(notFound){
			  console.log("did not find this name in old subs: " +this[i].name);
			return this[i];				
		}
	  }	
};`
Greetings!

**Comment by nmynarcik** [comment]
It's cool to see someone else interested in this. I've stopped supporting it, and glad you are picking it up ;)

**Comment by nmynarcik** [comment]
Feel free to close this if you addressed it in your PR.
